name: today-in-history

on:
  schedule:
    - cron: '0 8 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    container: python:3.8
    steps:
      - uses: actions/checkout@v1
      - name: update today-in-history
        run: |
          pip install pipenv
          pipenv install --ignore-pipfile
          pipenv run python .github/workflows/today.py
      - name: commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        run: ./.github/workflows/git.sh